Add restaurants-api.js and basic functions
Brave-squirrels/CodersCamp2020.Project.JavaScript.RestaurantsAPI pull request #3
Opened 2020-12-24 11:41 UTC by MajStc

restaurants-api.js fetches info about restaurants based on city name and cuisines:
logo url
name
address
average rating

2020-12-24 12:10 UTC, kam237zasada requested changes
Ogólnie cała zasada działania spoko, jedynie zamiast tworzenia tablic z osobnymi właściwościami, to chyba lepiej moim zdaniem zwrócić tablicę zawierająca obiekty, a jako pojedynczy obiekt będzie to jedna restauracja z odpowiednimi właściwościami, bo w tym przypadku mająć w jednej tablicy nazwy, a w innej oceny, a w jeszcze innej logo i adres, to można się pogubić co do jakiej restauracji należy (wiadomo, że teoretycznie konkretny element tablicy w każdym pasuje do jednej restauracji, ale lepiej jak będzie zwracać obiekt zawirający tablicę obiektów)

2020-12-27 12:08 UTC, MajStc reviewed
Śmiga 👍

2020-12-29 17:43 UTC, kam237zasada approved these changes

2020-12-29 17:57 UTC, Veryyapeee approved these changes

2020-12-29 17:58 UTC, merged